#!/usr/bin/env python3
# lens_clipboard_manual.py
#
# Usa Google Lens a partir da imagem copiada no clipboard.
#
# Como usar:
#   python lens_clipboard_manual.py
#
# Depois:
#   PrintScreen
#   ou Win+Shift+S
#
# O script detecta a imagem nova, envia ao Google Lens e mostra resultado.
#
# Instalar:
#   pip install playwright pillow beautifulsoup4 lxml
#   python -m playwright install chromium

from __future__ import annotations

import argparse
import asyncio
import hashlib
import mimetypes
import re
import time
from pathlib import Path
from urllib.parse import parse_qs, urlencode, urljoin, urlparse, urlunparse

from bs4 import BeautifulSoup
from PIL import Image, ImageGrab
from playwright.async_api import async_playwright


USER_DATA_DIR = "chrome-lens-profile-clipboard"
OUTPUT_DIR = Path("lens_clipboard_outputs")
IMAGE_DIR = OUTPUT_DIR / "images"
URL_LOG = OUTPUT_DIR / "lens_urls.txt"

UPLOAD_URL = "https://lens.google.com/v3/upload"

USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/147.0.0.0 Safari/537.36"
)

AI_MARKERS = (
    "Visão geral criada por IA",
    "Visao geral criada por IA",
    "AI Overview",
    "Generated by AI",
)

NOISE = {
    "Ir para o conteúdo principal",
    "Ajuda sobre acessibilidade",
    "Feedback de acessibilidade",
    "Fazer login",
    "Modo IA",
    "Tudo",
    "Correspondências exatas",
    "Correspondências visuais",
    "Sobre esta imagem",
    "Feedback",
    "Resultados da pesquisa",
    "Links relacionados",
    "Mostrar mais",
    "Selecionar texto",
    "Traduzir",
}

STOP = {
    "Correspondências visuais",
    "Sobre esta imagem",
    "Links relacionados",
    "Resultados da pesquisa",
    "Feedback",
    "Mostrar mais",
}


def clean_lines(text: str) -> list[str]:
    lines = []
    for raw in text.replace("\r", "\n").split("\n"):
        line = " ".join(raw.strip().split())
        if line:
            lines.append(line)
    return lines


def image_hash(img: Image.Image) -> str:
    small = img.convert("RGB").resize((64, 64))
    return hashlib.sha256(small.tobytes()).hexdigest()


def get_clipboard_image() -> Image.Image | None:
    data = ImageGrab.grabclipboard()

    if isinstance(data, Image.Image):
        return data.convert("RGB")

    # Às vezes o clipboard vem como lista de arquivos.
    if isinstance(data, list):
        for item in data:
            path = Path(item)
            if path.exists() and path.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp", ".bmp"}:
                return Image.open(path).convert("RGB")

    return None


def save_clipboard_image(img: Image.Image, max_width: int, jpg_quality: int) -> Path:
    IMAGE_DIR.mkdir(parents=True, exist_ok=True)

    if max_width and img.width > max_width:
        ratio = max_width / img.width
        new_height = max(1, int(img.height * ratio))
        img = img.resize((max_width, new_height), Image.Resampling.LANCZOS)

    ts = time.strftime("%Y%m%d_%H%M%S")
    out = IMAGE_DIR / f"clipboard_{ts}.jpg"
    img.save(out, format="JPEG", quality=jpg_quality, optimize=True)
    return out


def build_upload_url(viewport_width: int = 1280, viewport_height: int = 1000) -> str:
    params = {
        "ep": "gsbubb",
        "st": str(int(time.time() * 1000)),
        "authuser": "0",
        "hl": "pt-BR",
        "vpw": str(viewport_width),
        "vph": str(viewport_height),
    }
    return UPLOAD_URL + "?" + urlencode(params)


def force_lens_normal_url(url: str) -> str:
    parsed = urlparse(url)
    qs = parse_qs(parsed.query, keep_blank_values=True)

    # Sem input textual, sem q/oq, Lens visual normal.
    qs.pop("q", None)
    qs.pop("oq", None)
    qs["udm"] = ["26"]
    qs["lns_mode"] = ["un"]
    qs["hl"] = ["pt-BR"]

    new_query = urlencode(qs, doseq=True)
    return urlunparse((parsed.scheme, parsed.netloc, parsed.path, parsed.params, new_query, parsed.fragment))


def extract_answer(body_text: str) -> str:
    lines = clean_lines(body_text)

    for i, line in enumerate(lines):
        if any(marker in line for marker in AI_MARKERS):
            answer = []
            for item in lines[i + 1:]:
                if item in STOP:
                    break
                if item in NOISE:
                    continue
                if any(marker in item for marker in AI_MARKERS):
                    continue

                answer.append(item)

                if len(answer) >= 8:
                    break

            if answer:
                return "\n".join(answer)

    useful = []
    for line in lines:
        if line in NOISE or line in STOP:
            continue

        if re.fullmatch(r"(Brasil|Privacidade|Termos|Ajuda|Enviar feedback)", line, re.I):
            continue

        if len(line) < 8:
            continue

        useful.append(line)

        if len(useful) >= 10:
            break

    return "\n".join(useful) if useful else "Sem resultado textual carregado."


def extract_refs(html: str, max_links: int = 4) -> list[tuple[str, str]]:
    soup = BeautifulSoup(html, "lxml")
    refs = []
    seen = set()

    blocked = (
        "support.google.com",
        "policies.google.com",
        "/preferences",
        "/setprefs",
        "httpservice/retry/enablejs",
        "google.com/webhp",
        "google.com.br/intl",
        "source=lnt",
        "tbs=qdr:",
    )

    for a in soup.select("a[href]"):
        title = " ".join(a.get_text(" ", strip=True).split())
        href = a.get("href", "")

        if href.startswith("/"):
            href = "https://www.google.com" + href

        if not href or href.startswith("javascript:") or href.startswith("#"):
            continue

        if any(b in href for b in blocked):
            continue

        if title in NOISE or title in STOP:
            continue

        if href.startswith("https://www.google.com/search") and len(title) < 8:
            continue

        key = (title.lower(), href)
        if key in seen:
            continue

        seen.add(key)
        refs.append((title[:140] if title else href[:140], href))

        if len(refs) >= max_links:
            break

    return refs


class ClipboardLens:
    def __init__(
        self,
        show: bool,
        upload_timeout: float,
        render_wait: float,
        max_links: int,
    ) -> None:
        self.show = show
        self.upload_timeout = upload_timeout
        self.render_wait = render_wait
        self.max_links = max_links
        self.playwright = None
        self.context = None
        self.viewport_width = 1280
        self.viewport_height = 1000

    async def __aenter__(self) -> "ClipboardLens":
        OUTPUT_DIR.mkdir(exist_ok=True)

        self.playwright = await async_playwright().start()

        self.context = await self.playwright.chromium.launch_persistent_context(
            USER_DATA_DIR,
            headless=not self.show,
            viewport={"width": self.viewport_width, "height": self.viewport_height},
            locale="pt-BR",
            user_agent=USER_AGENT,
            args=[
                "--disable-blink-features=AutomationControlled",
                "--disable-dev-shm-usage",
                "--no-sandbox",
                "--lang=pt-BR",
            ],
        )

        page = await self.context.new_page()
        try:
            await page.goto(
                "https://www.google.com/?hl=pt-BR",
                wait_until="domcontentloaded",
                timeout=30000,
            )
        finally:
            await page.close()

        return self

    async def __aexit__(self, exc_type, exc, tb) -> None:
        if self.context:
            try:
                await self.context.close()
            except Exception:
                pass

        if self.playwright:
            try:
                await self.playwright.stop()
            except Exception:
                pass

    async def upload(self, image_path: Path) -> tuple[str, int, float]:
        filename = image_path.name
        mime = mimetypes.guess_type(str(image_path))[0] or "image/jpeg"
        image_bytes = image_path.read_bytes()

        t0 = time.perf_counter()

        response = await self.context.request.post(
            build_upload_url(self.viewport_width, self.viewport_height),
            multipart={
                "encoded_image": {
                    "name": filename,
                    "mimeType": mime,
                    "buffer": image_bytes,
                },
                "image_content": "",
                "filename": filename,
                "hl": "pt-BR",
            },
            headers={
                "User-Agent": USER_AGENT,
                "Accept-Language": "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",
                "Origin": "https://lens.google.com",
                "Referer": "https://lens.google.com/",
            },
            max_redirects=0,
            timeout=int(self.upload_timeout * 1000),
        )

        elapsed = time.perf_counter() - t0
        location = response.headers.get("location", "")

        if not location:
            return "", response.status, elapsed

        final_url = force_lens_normal_url(urljoin("https://www.google.com", location))
        return final_url, response.status, elapsed

    async def render_result(self, url: str) -> tuple[str, list[tuple[str, str]], float, bool]:
        page = await self.context.new_page()
        t0 = time.perf_counter()

        try:
            await page.goto(url, wait_until="domcontentloaded", timeout=10000)

            deadline = time.perf_counter() + self.render_wait
            completed = False
            last_text = ""

            while time.perf_counter() < deadline:
                try:
                    last_text = await page.locator("body").inner_text(timeout=800)
                except Exception:
                    last_text = ""

                compact = " ".join(last_text.split())

                if "Nossos sistemas detectaram tráfego incomum" in compact:
                    return (
                        "BLOQUEIO GOOGLE: tráfego incomum detectado. Aguarde um tempo ou use intervalo maior.",
                        [],
                        time.perf_counter() - t0,
                        False,
                    )

                if any(marker in compact for marker in AI_MARKERS):
                    completed = True
                    break

                if "Correspondências visuais" in compact and len(compact) > 700:
                    completed = True
                    break

                if "Sobre esta imagem" in compact and len(compact) > 700:
                    completed = True
                    break

                await page.wait_for_timeout(250)

            try:
                body_text = await page.locator("body").inner_text(timeout=1000)
            except Exception:
                body_text = last_text

            try:
                html = await page.content()
            except Exception:
                html = ""

            return extract_answer(body_text), extract_refs(html, self.max_links), time.perf_counter() - t0, completed

        finally:
            try:
                await page.close()
            except Exception:
                pass

    async def analyze(self, image_path: Path) -> tuple[str, list[tuple[str, str]], dict[str, float], str, int, bool]:
        total_start = time.perf_counter()

        url, status, upload_time = await self.upload(image_path)

        if not url:
            return (
                f"Google não devolveu URL. Status={status}",
                [],
                {
                    "upload": upload_time,
                    "render": 0.0,
                    "total": time.perf_counter() - total_start,
                },
                "",
                status,
                False,
            )

        answer, refs, render_time, completed = await self.render_result(url)

        return (
            answer,
            refs,
            {
                "upload": upload_time,
                "render": render_time,
                "total": time.perf_counter() - total_start,
            },
            url,
            status,
            completed,
        )


def format_output(
    image_path: Path,
    answer: str,
    refs: list[tuple[str, str]],
    timings: dict[str, float],
    url: str,
    status: int,
    completed: bool,
) -> str:
    state = "ok" if completed else "parcial"

    parts = []
    parts.append(f"[imagem] {image_path}")
    parts.append(f"[upload] status={status}")
    parts.append("")
    parts.append("RESULTADO GOOGLE LENS")
    parts.append(answer)

    if refs:
        parts.append("\nREFERÊNCIAS")
        for i, (title, href) in enumerate(refs, 1):
            parts.append(f"{i}. {title}\n   {href}")

    parts.append(f"\nURL: {url}")
    parts.append(
        f"TEMPOS: upload={timings['upload']:.2f}s | render={timings['render']:.2f}s | total={timings['total']:.2f}s | status={state}"
    )

    return "\n".join(parts)


async def main_async() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--poll", type=float, default=0.5, help="Intervalo para checar clipboard")
    parser.add_argument("--max-width", type=int, default=1280)
    parser.add_argument("--jpg-quality", type=int, default=88)
    parser.add_argument("--upload-timeout", type=float, default=6.0)
    parser.add_argument("--render-wait", type=float, default=4.0)
    parser.add_argument("--max-links", type=int, default=4)
    parser.add_argument("--show", action="store_true")
    args = parser.parse_args()

    print("Lens clipboard manual iniciado.")
    print("Dê PrintScreen ou Win+Shift+S. Quando uma imagem nova cair no clipboard, eu mando pro Google Lens.")
    print("Sem loop automático de prints. Sem martelar Google. Para sair: Ctrl+C.")
    print()

    last_hash = ""

    async with ClipboardLens(
        show=args.show,
        upload_timeout=args.upload_timeout,
        render_wait=args.render_wait,
        max_links=args.max_links,
    ) as lens:
        while True:
            try:
                img = get_clipboard_image()

                if img is None:
                    await asyncio.sleep(args.poll)
                    continue

                current_hash = image_hash(img)

                if current_hash == last_hash:
                    await asyncio.sleep(args.poll)
                    continue

                last_hash = current_hash

                image_path = save_clipboard_image(
                    img,
                    max_width=args.max_width,
                    jpg_quality=args.jpg_quality,
                )

                print(f"[detectado] imagem nova no clipboard: {image_path}")

                answer, refs, timings, url, status, completed = await lens.analyze(image_path)

                print(format_output(image_path, answer, refs, timings, url, status, completed))
                print("-" * 60)

            except KeyboardInterrupt:
                raise

            except Exception as exc:
                print(f"[ERRO] {exc}")
                print("-" * 60)
                await asyncio.sleep(1)


def main() -> None:
    try:
        asyncio.run(main_async())
    except KeyboardInterrupt:
        print("\nEncerrando...")


if __name__ == "__main__":
    main()